server:
  image: registry.cn-hangzhou.aliyuncs.com/narlian/ngrok:1.0.1
  ports:
    - "8082:80"
    - "4432:443"
    - "4443:4443"
  volumes:
    - /data/ngrok:/myfiles
  environment:
    - DOMAIN="tunnel.fire8.cc"
  command: /bin/sh /server.sh
